name: cf workers

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      # Setup Rust yang proper & stabil
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown

      - uses: Swatinem/rust-cache@v2

      # (Jangan pre-build di sini; biarkan wrangler membaca [build].command di wrangler.toml)
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: npm
